namespace VideoEdit.UI;

partial class MainForm
{
    private System.ComponentModel.IContainer components = null;
    private TabControl tabControl;
    private TabPage tabOperations;
    private TabPage tabQueue;
    private TabPage tabProbe;
    private TabPage tabConfig;
    private TabPage tabHistory;
    private ComboBox cmbOperation;
    private ComboBox cmbPreset;
    private TextBox txtInputPaths;
    private TextBox txtOutputPath;
    private TextBox txtStart;
    private TextBox txtEnd;
    private TextBox txtDuration;
    private CheckBox chkAccurateSeek;
    private CheckBox chkVideoCopy;
    private CheckBox chkAudioCopy;
    private CheckBox chkOverwrite;
    private TextBox txtVideoCodec;
    private TextBox txtAudioCodec;
    private TextBox txtCrf;
    private TextBox txtPresetValue;
    private TextBox txtAudioBitrate;
    private TextBox txtPixelFormat;
    private TextBox txtContainer;
    private TextBox txtCommandPreview;
    private Button btnBrowseInput;
    private Button btnBrowseOutput;
    private Button btnPreview;
    private Button btnEnqueue;
    private GroupBox grpTrim;
    private DataGridView queueGrid;
    private ProgressBar progressBar;
    private TextBox txtLiveLog;
    private Button btnCancelJob;
    private Label lblQueueStatus;
    private TextBox txtProbeInput;
    private Button btnBrowseProbeInput;
    private Button btnRunProbe;
    private TextBox txtProbeOutput;
    private TextBox txtProbeCommand;
    private Button btnExportProbeText;
    private Button btnExportProbeJson;
    private TextBox txtFfmpegDir;
    private Button btnBrowseFfmpegDir;
    private CheckBox chkShowCommand;
    private Button btnSaveSettings;
    private Label lblToolDiagnostic;
    private DataGridView historyGrid;
    private TextBox txtHistoryDetails;

    protected override void Dispose(bool disposing)
    {
        if (disposing && (components != null))
        {
            components.Dispose();
        }

        base.Dispose(disposing);
    }

    private void InitializeComponent()
    {
        components = new System.ComponentModel.Container();
        tabControl = new TabControl();
        tabOperations = new TabPage();
        tabQueue = new TabPage();
        tabProbe = new TabPage();
        tabConfig = new TabPage();
        tabHistory = new TabPage();
        cmbOperation = new ComboBox();
        cmbPreset = new ComboBox();
        txtInputPaths = new TextBox();
        txtOutputPath = new TextBox();
        txtStart = new TextBox();
        txtEnd = new TextBox();
        txtDuration = new TextBox();
        chkAccurateSeek = new CheckBox();
        chkVideoCopy = new CheckBox();
        chkAudioCopy = new CheckBox();
        chkOverwrite = new CheckBox();
        txtVideoCodec = new TextBox();
        txtAudioCodec = new TextBox();
        txtCrf = new TextBox();
        txtPresetValue = new TextBox();
        txtAudioBitrate = new TextBox();
        txtPixelFormat = new TextBox();
        txtContainer = new TextBox();
        txtCommandPreview = new TextBox();
        btnBrowseInput = new Button();
        btnBrowseOutput = new Button();
        btnPreview = new Button();
        btnEnqueue = new Button();
        grpTrim = new GroupBox();
        queueGrid = new DataGridView();
        progressBar = new ProgressBar();
        txtLiveLog = new TextBox();
        btnCancelJob = new Button();
        lblQueueStatus = new Label();
        txtProbeInput = new TextBox();
        btnBrowseProbeInput = new Button();
        btnRunProbe = new Button();
        txtProbeOutput = new TextBox();
        txtProbeCommand = new TextBox();
        btnExportProbeText = new Button();
        btnExportProbeJson = new Button();
        txtFfmpegDir = new TextBox();
        btnBrowseFfmpegDir = new Button();
        chkShowCommand = new CheckBox();
        btnSaveSettings = new Button();
        lblToolDiagnostic = new Label();
        historyGrid = new DataGridView();
        txtHistoryDetails = new TextBox();
        tabControl.SuspendLayout();
        tabOperations.SuspendLayout();
        tabQueue.SuspendLayout();
        tabProbe.SuspendLayout();
        tabConfig.SuspendLayout();
        tabHistory.SuspendLayout();
        grpTrim.SuspendLayout();
        ((System.ComponentModel.ISupportInitialize)queueGrid).BeginInit();
        ((System.ComponentModel.ISupportInitialize)historyGrid).BeginInit();
        SuspendLayout();
        AutoScaleDimensions = new SizeF(8F, 20F);
        AutoScaleMode = AutoScaleMode.Font;
        ClientSize = new Size(1280, 820);
        Controls.Add(tabControl);
        MinimumSize = new Size(1100, 760);
        StartPosition = FormStartPosition.CenterScreen;
        Text = "VideoEdit - Frontend técnico FFmpeg";
        tabControl.Controls.Add(tabOperations);
        tabControl.Controls.Add(tabQueue);
        tabControl.Controls.Add(tabProbe);
        tabControl.Controls.Add(tabConfig);
        tabControl.Controls.Add(tabHistory);
        tabControl.Dock = DockStyle.Fill;
        tabControl.Location = new Point(0, 0);
        tabControl.Name = "tabControl";
        tabControl.SelectedIndex = 0;
        tabControl.Size = new Size(1280, 820);
        tabOperations.Location = new Point(4, 29);
        tabOperations.Name = "tabOperations";
        tabOperations.Padding = new Padding(12);
        tabOperations.Size = new Size(1272, 787);
        tabOperations.Text = "Operaciones";
        tabOperations.UseVisualStyleBackColor = true;
        tabQueue.Location = new Point(4, 29);
        tabQueue.Name = "tabQueue";
        tabQueue.Padding = new Padding(12);
        tabQueue.Size = new Size(1272, 787);
        tabQueue.Text = "Cola";
        tabQueue.UseVisualStyleBackColor = true;
        tabProbe.Location = new Point(4, 29);
        tabProbe.Name = "tabProbe";
        tabProbe.Padding = new Padding(12);
        tabProbe.Size = new Size(1272, 787);
        tabProbe.Text = "Inspección";
        tabProbe.UseVisualStyleBackColor = true;
        tabConfig.Location = new Point(4, 29);
        tabConfig.Name = "tabConfig";
        tabConfig.Padding = new Padding(12);
        tabConfig.Size = new Size(1272, 787);
        tabConfig.Text = "Configuración";
        tabConfig.UseVisualStyleBackColor = true;
        tabHistory.Location = new Point(4, 29);
        tabHistory.Name = "tabHistory";
        tabHistory.Padding = new Padding(12);
        tabHistory.Size = new Size(1272, 787);
        tabHistory.Text = "Historial";
        tabHistory.UseVisualStyleBackColor = true;
        InitializeOperationsTab();
        InitializeQueueTab();
        InitializeProbeTab();
        InitializeConfigTab();
        InitializeHistoryTab();
        tabControl.ResumeLayout(false);
        tabOperations.ResumeLayout(false);
        tabOperations.PerformLayout();
        tabQueue.ResumeLayout(false);
        tabQueue.PerformLayout();
        tabProbe.ResumeLayout(false);
        tabProbe.PerformLayout();
        tabConfig.ResumeLayout(false);
        tabConfig.PerformLayout();
        tabHistory.ResumeLayout(false);
        tabHistory.PerformLayout();
        grpTrim.ResumeLayout(false);
        grpTrim.PerformLayout();
        ((System.ComponentModel.ISupportInitialize)queueGrid).EndInit();
        ((System.ComponentModel.ISupportInitialize)historyGrid).EndInit();
        ResumeLayout(false);
    }

    private void InitializeOperationsTab()
    {
        tabOperations.Controls.Add(new Label { Location = new Point(16, 18), Size = new Size(120, 23), Text = "Operación" });
        tabOperations.Controls.Add(cmbOperation);
        tabOperations.Controls.Add(new Label { Location = new Point(260, 18), Size = new Size(120, 23), Text = "Preset" });
        tabOperations.Controls.Add(cmbPreset);
        tabOperations.Controls.Add(new Label { Location = new Point(16, 58), Size = new Size(150, 23), Text = "Entradas (1 por línea)" });
        tabOperations.Controls.Add(txtInputPaths);
        tabOperations.Controls.Add(btnBrowseInput);
        tabOperations.Controls.Add(new Label { Location = new Point(16, 238), Size = new Size(120, 23), Text = "Salida" });
        tabOperations.Controls.Add(txtOutputPath);
        tabOperations.Controls.Add(btnBrowseOutput);
        tabOperations.Controls.Add(grpTrim);
        tabOperations.Controls.Add(new Label { Location = new Point(16, 392), Size = new Size(200, 23), Text = "Parámetros técnicos" });
        tabOperations.Controls.Add(new Label { Location = new Point(16, 424), Size = new Size(80, 23), Text = "Video" });
        tabOperations.Controls.Add(txtVideoCodec);
        tabOperations.Controls.Add(new Label { Location = new Point(228, 424), Size = new Size(80, 23), Text = "Audio" });
        tabOperations.Controls.Add(txtAudioCodec);
        tabOperations.Controls.Add(new Label { Location = new Point(440, 424), Size = new Size(80, 23), Text = "CRF" });
        tabOperations.Controls.Add(txtCrf);
        tabOperations.Controls.Add(new Label { Location = new Point(16, 468), Size = new Size(80, 23), Text = "Preset" });
        tabOperations.Controls.Add(txtPresetValue);
        tabOperations.Controls.Add(new Label { Location = new Point(228, 468), Size = new Size(100, 23), Text = "Bitrate audio" });
        tabOperations.Controls.Add(txtAudioBitrate);
        tabOperations.Controls.Add(new Label { Location = new Point(440, 468), Size = new Size(80, 23), Text = "Pixel fmt" });
        tabOperations.Controls.Add(txtPixelFormat);
        tabOperations.Controls.Add(new Label { Location = new Point(652, 468), Size = new Size(90, 23), Text = "Contenedor" });
        tabOperations.Controls.Add(txtContainer);
        tabOperations.Controls.Add(chkAudioCopy);
        tabOperations.Controls.Add(chkVideoCopy);
        tabOperations.Controls.Add(chkOverwrite);
        tabOperations.Controls.Add(new Label { Location = new Point(16, 562), Size = new Size(200, 23), Text = "Vista previa del comando" });
        tabOperations.Controls.Add(txtCommandPreview);
        tabOperations.Controls.Add(btnPreview);
        tabOperations.Controls.Add(btnEnqueue);
        cmbOperation.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbOperation.Location = new Point(16, 41);
        cmbOperation.Size = new Size(220, 28);
        cmbPreset.DropDownStyle = ComboBoxStyle.DropDownList;
        cmbPreset.Location = new Point(260, 41);
        cmbPreset.Size = new Size(280, 28);
        txtInputPaths.Location = new Point(16, 82);
        txtInputPaths.Multiline = true;
        txtInputPaths.ScrollBars = ScrollBars.Vertical;
        txtInputPaths.Size = new Size(900, 140);
        btnBrowseInput.Location = new Point(932, 82);
        btnBrowseInput.Size = new Size(170, 32);
        btnBrowseInput.Text = "Seleccionar...";
        txtOutputPath.Location = new Point(16, 262);
        txtOutputPath.Size = new Size(900, 27);
        btnBrowseOutput.Location = new Point(932, 260);
        btnBrowseOutput.Size = new Size(170, 32);
        btnBrowseOutput.Text = "Guardar como...";
        grpTrim.Controls.Add(new Label { Location = new Point(16, 26), Size = new Size(80, 23), Text = "Inicio" });
        grpTrim.Controls.Add(txtStart);
        grpTrim.Controls.Add(new Label { Location = new Point(228, 26), Size = new Size(80, 23), Text = "Fin" });
        grpTrim.Controls.Add(txtEnd);
        grpTrim.Controls.Add(new Label { Location = new Point(440, 26), Size = new Size(90, 23), Text = "Duración" });
        grpTrim.Controls.Add(txtDuration);
        grpTrim.Controls.Add(chkAccurateSeek);
        grpTrim.Location = new Point(16, 308);
        grpTrim.Size = new Size(1086, 72);
        grpTrim.Text = "Recorte";
        txtStart.Location = new Point(16, 47);
        txtStart.Size = new Size(180, 27);
        txtEnd.Location = new Point(228, 47);
        txtEnd.Size = new Size(180, 27);
        txtDuration.Location = new Point(440, 47);
        txtDuration.Size = new Size(180, 27);
        chkAccurateSeek.Location = new Point(652, 48);
        chkAccurateSeek.Size = new Size(220, 24);
        chkAccurateSeek.Text = "Seek preciso (reencode)";
        txtVideoCodec.Location = new Point(16, 448);
        txtVideoCodec.Size = new Size(180, 27);
        txtAudioCodec.Location = new Point(228, 448);
        txtAudioCodec.Size = new Size(180, 27);
        txtCrf.Location = new Point(440, 448);
        txtCrf.Size = new Size(180, 27);
        txtPresetValue.Location = new Point(16, 492);
        txtPresetValue.Size = new Size(180, 27);
        txtAudioBitrate.Location = new Point(228, 492);
        txtAudioBitrate.Size = new Size(180, 27);
        txtPixelFormat.Location = new Point(440, 492);
        txtPixelFormat.Size = new Size(180, 27);
        txtContainer.Location = new Point(652, 492);
        txtContainer.Size = new Size(120, 27);
        chkAudioCopy.Location = new Point(812, 447);
        chkAudioCopy.Size = new Size(120, 24);
        chkAudioCopy.Text = "Audio copy";
        chkVideoCopy.Location = new Point(812, 491);
        chkVideoCopy.Size = new Size(120, 24);
        chkVideoCopy.Text = "Video copy";
        chkOverwrite.Location = new Point(952, 447);
        chkOverwrite.Size = new Size(150, 24);
        chkOverwrite.Text = "Sobrescribir";
        txtCommandPreview.Location = new Point(16, 586);
        txtCommandPreview.Multiline = true;
        txtCommandPreview.ReadOnly = true;
        txtCommandPreview.ScrollBars = ScrollBars.Vertical;
        txtCommandPreview.Size = new Size(1086, 110);
        btnPreview.Location = new Point(16, 712);
        btnPreview.Size = new Size(160, 34);
        btnPreview.Text = "Actualizar preview";
        btnEnqueue.Location = new Point(942, 712);
        btnEnqueue.Size = new Size(160, 34);
        btnEnqueue.Text = "Agregar a cola";
    }

    private void InitializeQueueTab()
    {
        tabQueue.Controls.Add(queueGrid);
        tabQueue.Controls.Add(progressBar);
        tabQueue.Controls.Add(lblQueueStatus);
        tabQueue.Controls.Add(txtLiveLog);
        tabQueue.Controls.Add(btnCancelJob);
        queueGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        queueGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        queueGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Name", HeaderText = "Job", Width = 280 });
        queueGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "Status", HeaderText = "Estado", Width = 120 });
        queueGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "CreatedAt", HeaderText = "Creado", Width = 180 });
        queueGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "LastMessage", HeaderText = "Detalle", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
        queueGrid.Location = new Point(16, 18);
        queueGrid.RowHeadersVisible = false;
        queueGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        queueGrid.Size = new Size(1238, 280);
        progressBar.Location = new Point(16, 316);
        progressBar.Size = new Size(1060, 24);
        lblQueueStatus.Location = new Point(16, 350);
        lblQueueStatus.Size = new Size(1060, 23);
        lblQueueStatus.Text = "Esperando trabajos...";
        btnCancelJob.Location = new Point(1094, 312);
        btnCancelJob.Size = new Size(160, 32);
        btnCancelJob.Text = "Cancelar activo";
        txtLiveLog.Location = new Point(16, 386);
        txtLiveLog.Multiline = true;
        txtLiveLog.ReadOnly = true;
        txtLiveLog.ScrollBars = ScrollBars.Both;
        txtLiveLog.Size = new Size(1238, 370);
    }

    private void InitializeProbeTab()
    {
        tabProbe.Controls.Add(new Label { Location = new Point(16, 18), Size = new Size(160, 23), Text = "Archivo a inspeccionar" });
        tabProbe.Controls.Add(txtProbeInput);
        tabProbe.Controls.Add(btnBrowseProbeInput);
        tabProbe.Controls.Add(btnRunProbe);
        tabProbe.Controls.Add(new Label { Location = new Point(16, 92), Size = new Size(160, 23), Text = "Comando ffprobe" });
        tabProbe.Controls.Add(txtProbeCommand);
        tabProbe.Controls.Add(txtProbeOutput);
        tabProbe.Controls.Add(btnExportProbeText);
        tabProbe.Controls.Add(btnExportProbeJson);
        txtProbeInput.Location = new Point(16, 42);
        txtProbeInput.Size = new Size(900, 27);
        btnBrowseProbeInput.Location = new Point(932, 40);
        btnBrowseProbeInput.Size = new Size(150, 32);
        btnBrowseProbeInput.Text = "Seleccionar...";
        btnRunProbe.Location = new Point(1098, 40);
        btnRunProbe.Size = new Size(156, 32);
        btnRunProbe.Text = "Ejecutar ffprobe";
        txtProbeCommand.Location = new Point(16, 116);
        txtProbeCommand.Multiline = true;
        txtProbeCommand.ReadOnly = true;
        txtProbeCommand.ScrollBars = ScrollBars.Vertical;
        txtProbeCommand.Size = new Size(1238, 70);
        txtProbeOutput.Location = new Point(16, 206);
        txtProbeOutput.Multiline = true;
        txtProbeOutput.ReadOnly = true;
        txtProbeOutput.ScrollBars = ScrollBars.Both;
        txtProbeOutput.Size = new Size(1238, 510);
        btnExportProbeText.Location = new Point(16, 730);
        btnExportProbeText.Size = new Size(170, 32);
        btnExportProbeText.Text = "Exportar texto";
        btnExportProbeJson.Location = new Point(202, 730);
        btnExportProbeJson.Size = new Size(170, 32);
        btnExportProbeJson.Text = "Exportar JSON";
    }

    private void InitializeConfigTab()
    {
        tabConfig.Controls.Add(new Label { Location = new Point(16, 24), Size = new Size(220, 23), Text = "Carpeta bin de FFmpeg (opcional)" });
        tabConfig.Controls.Add(txtFfmpegDir);
        tabConfig.Controls.Add(btnBrowseFfmpegDir);
        tabConfig.Controls.Add(chkShowCommand);
        tabConfig.Controls.Add(btnSaveSettings);
        tabConfig.Controls.Add(lblToolDiagnostic);
        txtFfmpegDir.Location = new Point(16, 50);
        txtFfmpegDir.Size = new Size(860, 27);
        btnBrowseFfmpegDir.Location = new Point(892, 48);
        btnBrowseFfmpegDir.Size = new Size(170, 32);
        btnBrowseFfmpegDir.Text = "Buscar carpeta...";
        chkShowCommand.Location = new Point(16, 106);
        chkShowCommand.Size = new Size(260, 24);
        chkShowCommand.Text = "Mostrar preview de comando";
        btnSaveSettings.Location = new Point(16, 146);
        btnSaveSettings.Size = new Size(170, 34);
        btnSaveSettings.Text = "Guardar configuración";
        lblToolDiagnostic.Location = new Point(16, 198);
        lblToolDiagnostic.Size = new Size(900, 60);
    }

    private void InitializeHistoryTab()
    {
        tabHistory.Controls.Add(historyGrid);
        tabHistory.Controls.Add(txtHistoryDetails);
        historyGrid.Anchor = AnchorStyles.Top | AnchorStyles.Left | AnchorStyles.Right;
        historyGrid.ColumnHeadersHeightSizeMode = DataGridViewColumnHeadersHeightSizeMode.AutoSize;
        historyGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "CreatedAt", HeaderText = "Fecha", Width = 180 });
        historyGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "JobName", HeaderText = "Trabajo", Width = 220 });
        historyGrid.Columns.Add(new DataGridViewCheckBoxColumn { DataPropertyName = "Success", HeaderText = "OK", Width = 60 });
        historyGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "ExitCode", HeaderText = "Exit", Width = 80 });
        historyGrid.Columns.Add(new DataGridViewTextBoxColumn { DataPropertyName = "CommandText", HeaderText = "Comando", AutoSizeMode = DataGridViewAutoSizeColumnMode.Fill });
        historyGrid.Location = new Point(16, 18);
        historyGrid.RowHeadersVisible = false;
        historyGrid.SelectionMode = DataGridViewSelectionMode.FullRowSelect;
        historyGrid.Size = new Size(1238, 250);
        txtHistoryDetails.Location = new Point(16, 286);
        txtHistoryDetails.Multiline = true;
        txtHistoryDetails.ReadOnly = true;
        txtHistoryDetails.ScrollBars = ScrollBars.Both;
        txtHistoryDetails.Size = new Size(1238, 470);
    }
}
